### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by noeldum** [psychogenic/psypnp#3]
Hi Pat,

It is not really clear how to install psypnp. It says to put the content of lib data and script under .openpnp2/scripts.

Does it means
cp psypnp-main/lib/* ~/.openpnp2/scripts/
cp psypnp-main/data/* ~/.openpnp2/scripts/
cp psypnp-main/scripts/* ~/.openpnp2/scripts/
?

doing so leads to a conflict of the config folder for example.

Or if I copy data lib and scripts folders themselves under scripts it can not find the psypnp module.
cp lib data scripts ~/.openpnp2/

Could you show us an example of a directory tree under ~/.openpnp2/scripts ?

**Comment by psychogenic** [comment]
Ah, sorry about that Noël.  
So it's in essence
cp -R psypnp-main/lib/ ~/.openpnp2
cp -R psypnp-main/data ~/.openpnp2
cp -R psypnp-main/scripts/* ~/.openpnp2/scripts/

So the OpenPnP dir has
 lib/
 data/
 scripts/feeder
 scripts/job
etc
within.

**Comment by noeldum** [comment]
Right. lib and data just below .openpnp2 then. That works. Thanks a lot.
